### ISSUE TITLE
Unable to build mu from master

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1342]
## Expected or desired behavior

Build mu.

## Actual behavior

Mu stop building at: 
2aa299b * | mu: add mu_msg_iter_is_(first|last)

```
make[3] : on entre dans le répertoire « /home/thierry/labo/github/mu/lib »
  CC       mu-container.lo
  CXX      mu-msg-iter.lo
mu-msg-iter.cc: In function ‘gboolean mu_msg_iter_is_last(MuMsgIter*)’:
mu-msg-iter.cc:353:24: error: no match for ‘operator+’ (operand types are ‘Xapian::MSet::const_iterator {aka Xapian::MSetIterator}’ and ‘int’)
  return iter->cursor() + 1 == iter->matches().end();
                        ^
Makefile:643 : la recette pour la cible « mu-msg-iter.lo » a échouée
make[3]: *** [mu-msg-iter.lo] Erreur 1
make[3] : on quitte le répertoire « /home/thierry/labo/github/mu/lib »
Makefile:662 : la recette pour la cible « all-recursive » a échouée
make[2]: *** [all-recursive] Erreur 1
make[2] : on quitte le répertoire « /home/thierry/labo/github/mu/lib »
Makefile:538 : la recette pour la cible « all-recursive » a échouée
make[1]: *** [all-recursive] Erreur 1
make[1] : on quitte le répertoire « /home/thierry/labo/github/mu »
Makefile:448 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```
 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

**Comment by djcb** [comment]
I suspect it's a Xapian API thing, what version are you using?
(it happily builds with 1.4.9)

**Comment by dbgns** [comment]
I came across the same problem, and when I installed the Xapian 1.4.9 bugs occurred like this:
![image](https://user-images.githubusercontent.com/37951601/49986462-08630e00-ffab-11e8-96fa-5a7166dc5669.png)
The command I used was `autoreconf -i && ./configure --prefix=/usr && make`

**Comment by thierryvolpiatto** [comment]
@djcb sorry for late reply, yes I could build mu successfully with 1.4.9.
@dbgns probably you have to run first `make clean`?

**Comment by haji-ali** [comment]
I had the same problem and an update to xapian 1.4.9 resolved it. autogen should perhaps check this requirement.

**Comment by djcb** [comment]
Yeah, bumped the minimum required Xapian version to 1.4.0

**Comment by anguslee** [comment]
With Xapian version 1.4.5, the above error still exists. Maybe the minimum required version should be bumped again.

mu configuration is complete.
------------------------------------------------
mu version                           : 1.2.0

Xapian version                       : 1.4.5
GLib version                         : 2.60.6
GMime version                        : 3.2.3
Json-Glib version                    : 1.4.4
Guile version                        : 2.2
Emacs version                        : GNU Emacs 26.2

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------


Now, type 'make' (or 'gmake') to build mu

**Comment by djcb** [comment]
@anguslee, can you share the exact errors you're getting? They should be a bit different from the earlier ones...

**Comment by anguslee** [comment]
> @anguslee, can you share the exact errors you're getting? They should be a bit different from the earlier ones...

/usr/include/xapian/version.h:30:2: warning: #warning that of the compiler used to build the library. If linking fails [-Wcpp]
   30 | #warning that of the compiler used to build the library. If linking fails
      |  ^~~~~~~
/usr/include/xapian/version.h:31:2: warning: #warning due to missing symbols, this is probably the reason why. [-Wcpp]
   31 | #warning due to missing symbols, this is probably the reason why.
      |  ^~~~~~~
/usr/include/xapian/version.h:32:2: warning: #warning The Xapian library was built with g++ 7.2.0 [-Wcpp]
   32 | #warning The Xapian library was built with g++ 7.2.0
      |  ^~~~~~~
  CC       mu-str.lo
  CC       mu-threader.lo
  CC       mu-util.lo
  CXXLD    libmu.la
make[3]: Leaving directory '/home/angus/Downloads/mu-1.2.0/lib'
Making all in tests
make[3]: Entering directory '/home/angus/Downloads/mu-1.2.0/lib/tests'
make  all-am
make[4]: Entering directory '/home/angus/Downloads/mu-1.2.0/lib/tests'
  CC       test-mu-util.o
  CXX      dummy.o
  CC       test-mu-common.lo
  CCLD     libtestmucommon.la
  CXXLD    test-mu-util
  CC       test-mu-str.o
  CXXLD    test-mu-str
  CC       test-mu-maildir.o
  CXXLD    test-mu-maildir
  CC       test-mu-msg-fields.o
  CXXLD    test-mu-msg-fields
  CC       test-mu-msg.o
  CXXLD    test-mu-msg
/usr/lib64/gcc/x86_64-slackware-linux/9.1.0/../../../../x86_64-slackware-linux/bin/ld: ./.libs/libtestmucommon.a(mu-msg-doc.o): in function `mu_msg_doc_get_str_field':
/home/angus/Downloads/mu-1.2.0/lib/mu-msg-doc.cc:79: undefined reference to `Xapian::Document::get_value[abi:cxx11](unsigned int) const'
/usr/lib64/gcc/x86_64-slackware-linux/9.1.0/../../../../x86_64-slackware-linux/bin/ld: ./.libs/libtestmucommon.a(mu-msg-doc.o): in function `mu_msg_doc_get_str_list_field':
/home/angus/Downloads/mu-1.2.0/lib/mu-msg-doc.cc:95: undefined reference to `Xapian::Document::get_value[abi:cxx11](unsigned int) const'
/usr/lib64/gcc/x86_64-slackware-linux/9.1.0/../../../../x86_64-slackware-linux/bin/ld: ./.libs/libtestmucommon.a(mu-msg-doc.o): in function `mu_msg_doc_get_num_field':
/home/angus/Downloads/mu-1.2.0/lib/mu-msg-doc.cc:110: undefined reference to `Xapian::Document::get_value[abi:cxx11](unsigned int) const'
/usr/lib64/gcc/x86_64-slackware-linux/9.1.0/../../../../x86_64-slackware-linux/bin/ld: /home/angus/Downloads/mu-1.2.0/lib/mu-msg-doc.cc:118: undefined reference to `Xapian::sortable_unserialise(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:651: test-mu-msg] Error 1
make[4]: Leaving directory '/home/angus/Downloads/mu-1.2.0/lib/tests'
make[3]: *** [Makefile:579: all] Error 2
make[3]: Leaving directory '/home/angus/Downloads/mu-1.2.0/lib/tests'
make[2]: *** [Makefile:708: all-recursive] Error 1
make[2]: Leaving directory '/home/angus/Downloads/mu-1.2.0/lib'
make[1]: *** [Makefile:539: all-recursive] Error 1
make[1]: Leaving directory '/home/angus/Downloads/mu-1.2.0

**Comment by anguslee** [comment]
mu version                           : 1.2.0

Xapian version                       : 1.4.5
GLib version                         : 2.60.6
GMime version                        : 3.2.3
Json-Glib version                    : 1.4.4
Guile version                        : 2.2
Emacs version                        : GNU Emacs 26.2

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes

**Comment by anguslee** [comment]
Those are the error messages I get from running 'make' and my output after running './configure'

**Comment by dochego** [comment]
After the recent commit, the current mu version compiles fine again for me with xapian 1.4.5

    ------------------------------------------------
    mu version                           : 1.3.4
    
    Xapian version                       : 1.4.5
    GLib version                         : 2.56.4
    GMime version                        : 3.2.0
    Json-Glib version                    : 1.4.2
    GTK+ version                         : 3.22.30
    Webkit2/GTK+ version                 : 2.24.2
    Emacs version                        : GNU Emacs 26.2.90
    
    Have wordexp                         : yes
    Build mu4e emacs frontend            : yes
    Build 'mug' toy-ui (gtk+/webkit)     : yes
    McCabe's Cyclomatic Complexity tool  : no
    
    Have direntry->d_ino                 : yes
    Have direntry->d_type                : yes
    ------------------------------------------------

**Comment by anguslee** [comment]
I don't think this commit works so good. I switched to the master branch in my mu repository, the error is still there:

<pre>
mu version                           : 1.3.4

Xapian version                       : 1.4.5
GLib version                         : 2.60.6
GMime version                        : 3.2.3
Json-Glib version                    : 1.4.4
Guile version                        : 2.2
Emacs version                        : GNU Emacs 26.2

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
</pre>

<pre>
$ git log
commit 6b5a31f45aaff380faa6f339ab43b1ad3a6b02e6 (HEAD -> master, origin/master, origin/HEAD)
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Sat Aug 3 11:17:00 2019 +0300

    configure.ac: Fix make distcheck
    
    Avoid msg2pdf.

commit 74f9f78ec085fc22ffa80c5a98792cda092f0c63
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Sat Aug 3 11:06:50 2019 +0300

    lib: Don't use Xapian::DatabaseNotFoundError, it's too new
    
    Xapian::DatabaseNotFoundError only arrived with Xapian 1.4.10.

commit 70cb10eddb3ed35c813898186c3c4f3a87404a9d
Author: Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
Date:   Thu Aug 1 22:43:06 2019 +0300

    NEWS.org: update with all the latest gossip
</pre>
