### ISSUE TITLE
[mu bug] ‘g_mime_object_write_content_to_stream’ was not declared in this scope

### ISSUE THREAD

**Issue by robstewart57** [djcb/mu#2859]
**Describe the bug**

Try to compile with da9cd06fceeee54623000637fedfa93fba8138a9 

```
[41/166] Compiling C++ object scm/libmu-scm.a.p/mu-scm-mime.cc.o
FAILED: scm/libmu-scm.a.p/mu-scm-mime.cc.o 
c++ -Iscm/libmu-scm.a.p -Iscm -I../scm -I. -I.. -Ilib -I../lib -Ilib/message -I../lib/message -Ilib/utils -I../lib/utils -I../thirdparty -I/usr/include/guile/3.0 -I/usr/include/gmime-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O2 -g -Wno-unused-parameter -Wno-cast-function-type -Wformat-security -Wformat=2 -Wstack-protector -fstack-protector-strong -Wno-switch-enum -Wno-array-bounds -Wno-stringop-overflow -Wno-volatile -DHAVE_CONFIG_H -fPIC -pthread -DFMT_HEADER_ONLY -D_LARGEFILE64_SOURCE '-DMU_SCM_DIR="/usr/local/share/mu/scm"' -MD -MQ scm/libmu-scm.a.p/mu-scm-mime.cc.o -MF scm/libmu-scm.a.p/mu-scm-mime.cc.o.d -o scm/libmu-scm.a.p/mu-scm-mime.cc.o -c ../scm/mu-scm-mime.cc
../scm/mu-scm-mime.cc: In function ‘GMimeStream* get_stream(GMimePart*, bool)’:
../scm/mu-scm-mime.cc:133:23: error: ‘g_mime_object_write_content_to_stream’ was not declared in this scope; did you mean ‘g_mime_object_write_to_stream’?
  133 |                 res = g_mime_object_write_content_to_stream(
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       g_mime_object_write_to_stream
```

**How to Reproduce**

    rm -rf build/*
    meson build
    ninja -C build

Bug introduced in https://github.com/djcb/mu/commit/b02aa5768645d1df7da42195f1fbacd0a62e7d1c

**Environment**

Ubuntu 22.04.5 LTS. GNU Emacs 31.0.50 Development version 3860562a715b on master branch; build date 2025-03-15.

**Comment by djcb** [comment]
Ah, right... the minimal gmime that  mu requires doesn't have function yet. I'll add  a check. Thanks!
