### ISSUE TITLE
[misc] Not able to compile on OSX

### ISSUE THREAD

**Issue by marcbowes** [djcb/mu#2074]
**Note**: for questions, please use the mailing-list: https://groups.google.com/g/mu-discuss

**Describe the issue**
I've been building on OSX for a number of years, via:

```
git pull
make install
```

I'm probably a few months out of date! I learned about the multi-core indexing feature that was recently added, but after a pull I can no longer build. Loads of these:

```
In file included from mu-guile.cc:20:
In file included from ./mu-guile.hh:25:
In file included from ../lib/mu-query.hh:26:
In file included from ../lib/mu-store.hh:23:
In file included from ../lib/mu-msg.hh:28:
In file included from ../lib/utils/mu-option.hh:17:
../lib/utils/optional.hpp:2035:19: error: too many arguments provided to function-like macro invocation
                  "T must be move constructible and convertible from U");
                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__config:916:13: note: macro 'static_assert' defined here
#    define static_assert(__b, __m) _Static_assert(__b, __m)
```

I don't really understand the error message because it looks like the macro takes 2 arguments and the callsite provides 2 arguments.

**Environment**
I'm on OSX 10.14.6.

**Comment by marcbowes** [comment]
If I *remove* the message argument:

```
modified   lib/utils/optional.hpp
@@ -2023,8 +2023,7 @@ public:
   /// Returns the stored value if there is one, otherwise returns `u`
   template <class U> constexpr T value_or(U &&u) const & noexcept {
     static_assert(std::is_copy_constructible<T>::value &&
-                      std::is_convertible<U &&, T>::value,
-                  "T must be copy constructible and convertible from U");
+                      std::is_convertible<U &&, T>::value);
     return has_value() ? **this : static_cast<T>(std::forward<U>(u));
   }
```

then it appears to compile that method:

```
In file included from test-option.cc:21:
In file included from ./mu-option.hh:17:
./optional.hpp:2026:58: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
                      std::is_convertible<U &&, T>::value);
                                                         ^
                                                         , ""
1 warning generated.
```

but fails with the next issue:

```
In file included from mu-guile.cc:20:
In file included from ./mu-guile.hh:25:
In file included from ../lib/mu-query.hh:26:
In file included from ../lib/mu-store.hh:23:
In file included from ../lib/mu-msg.hh:28:
In file included from ../lib/utils/mu-option.hh:17:
../lib/utils/optional.hpp:197:75: error: too many arguments provided to function-like macro invocation
    F, decltype(detail::invoke(std::declval<F>(), std::declval<Us>()...), void()),
                                                                          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__config:932:13: note: macro 'decltype' defined here
#    define decltype(__x) __decltype(__x)
            ^
```

I really know nothing about modern C++, so I'm guessing there has been some change to the build requirements of mu recently? But I don't know enough to look at the error and guess what those are.

**Comment by djcb** [comment]
One of the CI pipelines use MacOS, see e.g. https://github.com/djcb/mu/runs/3212646250, so it could/should work on MacOS (That runs Xcode_12.4) 

I guess the optional.hpp is a bit too clever for the compiler (the specific error is seen in other places)... perhaps you can try a different compiler?

**Comment by danielfleischer** [comment]
Did you run `./autogen.sh` before `make`, `make install`?

**Comment by marcbowes** [comment]
> Did you run `./autogen.sh` before `make`, `make install`?

Yes.


> One of the CI pipelines use MacOS, see e.g. https://github.com/djcb/mu/runs/3212646250, so it could/should work on MacOS (That runs Xcode_12.4)
> 
> I guess the optional.hpp is a bit too clever for the compiler (the specific error is seen in other places)... perhaps you can try a different compiler?

I saw that. I assume newer versions of OS X have a newer compiler or something like that. I'm trying to put off the update to Big Sur because it has a bunch of compatibility issues that aren't yet resolved.

**Comment by djcb** [comment]
The offending file is 3rd-party lib, and generally it goes out of its way to accommodate compilers... so a bit surprised it causes this trouble; would have expected that more people would be bitten by this.

**Comment by marcbowes** [comment]
I have good news, and bad news.

The good news is it compiles now on my laptop. The bad news is I upgraded to Big Sur, and my laptop broke. After reimaging to Big Sur, everything works.

**Comment by djcb** [comment]
Thanks... going to close this then. Good luck with Big Sur!
