### ISSUE TITLE
‘add_history’ was not declared in this scope

### ISSUE THREAD

**Issue by robstewart57** [djcb/mu#1594]
## Expected or desired behavior

    autoreconf -i
    ./configure

Then:

    make

Which would compile.

Please describe the behavior you expected / want

mu compiles.

## Actual behavior

```
u-cmd-server.cc: In member function ‘void Readline::save_line(const string&)’:
mu-cmd-server.cc:1326:9: error: ‘add_history’ was not declared in this scope
 1326 |         add_history(line.c_str());
      |         ^~~~~~~~~~~
```

## Versions of mu, mu4e/emacs, operating system etc.

git commit 81d47bf21f7eb6bbddbcc359e96a681b57a1ab24

## Any other detail

This may have been caused by https://github.com/djcb/mu/commit/8d6d15109062ff1cbe9047e349bc7c9beae5584f#diff-7be5a4f9a79ee93913cd0953767b47d1L1299

Previously the `add_history(..)` function was wrapped with an `#ifdef HAVE_READLINE_HISTORY`, but now it is not: https://github.com/djcb/mu/commit/8d6d15109062ff1cbe9047e349bc7c9beae5584f#diff-7be5a4f9a79ee93913cd0953767b47d1R1324
