### ISSUE TITLE
Commit f33b0d6d does not compile without guile

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1588]
Commit f33b0d6d does not compile without Guile:
```
./autogen.sh --disable-guile
...
make
...
make[4]: Entering directory '/home/trch/software/mu/guile'
  CC       mu-guile.lo
mu-guile.c:27:10: fatal error: libguile.h: No such file or directory
   27 | #include <libguile.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:671: mu-guile.lo] Error 1
make[4]: Leaving directory '/home/trch/software/mu/guile'
make[3]: *** [Makefile:852: all-recursive] Error 1
make[3]: Leaving directory '/home/trch/software/mu/guile'
make[2]: *** [Makefile:566: all] Error 2
make[2]: Leaving directory '/home/trch/software/mu/guile'
make[1]: *** [Makefile:594: all-recursive] Error 1
make[1]: Leaving directory '/home/trch/software/mu'
make: *** [Makefile:504: all] Error 2
```
The absence of Guile should be detected by the configure script, especially because it does not work with Gluie-3.0, juste Guile-2.2.
